### ISSUE TITLE
RTTF Deposits Invoices calculating wrong values

### ISSUE THREAD

**Issue by artfulbodger** [spenmath/ScoutsEMSIssues#7]
rfdeposit.php is doubling up the quantities:

Group booking shows:
![groupaty](https://user-images.githubusercontent.com/7009338/34127656-d63b3240-e435-11e7-8bd0-7a688b6bd557.PNG)

Deposit Invoice shows:
![depositinvoice](https://user-images.githubusercontent.com/7009338/34127672-de84ab66-e435-11e7-9770-cd571c8d6835.PNG)

**Comment by artfulbodger** [comment]
Looks like the logic for the statement.php differs to the logic used for rfdeposit.php, an example where the statement page doesn't show any entries whereas the deposit shows values:

![groupaty](https://user-images.githubusercontent.com/7009338/34179432-c9004886-e502-11e7-8d2a-10fd639604e2.PNG)

![depositinvoice](https://user-images.githubusercontent.com/7009338/34179438-ce452fbe-e502-11e7-8098-a970931283fe.PNG)

**Comment by spenmath** [comment]
This is caused by the rfdeposit.php refering to the numbers they gave us when they registered. You asked for us to collect from the groups hw many people they think they will bring and the depsoit to be based on that. So group 1861 as screen shot in the first post, told us they were bringing 20/8 - it's a coincidence that they've uploaded only half of that number. As for the second screen shot, they told us they were brinigng 7/2 but haven't yet uploaded any names/emails. 

Here's the DB clip for the first screen shot. 
<img width="499" alt="screen shot 2017-12-23 at 15 20 07" src="https://user-images.githubusercontent.com/33485275/34320570-3c56ba50-e7f5-11e7-8788-66c917b5e71a.png">
